import { UserProfile, Department, Position, Meeting, Feedback, FollowUp, Task, FeedbackRequest, ConversationRequest, NotificationItem } from '../types';

export const TODAY_ISO = '2026-09-09';
export const TOMORROW_ISO = '2026-09-10';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-comercial',
    name: 'Comercial',
    description: 'Prospecção ativa, vendas consultivas B2B, gestão de pipeline e expansão de clientes.',
    managerId: 'usr-bruno',
    managerName: 'Bruno Fagundes',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'dept-marketing',
    name: 'Marketing',
    description: 'Branding, campanhas publicitárias, redes sociais, tráfego pago e geração de leads.',
    managerId: 'usr-camila',
    managerName: 'Camila Rocha',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'dept-site',
    name: 'Site',
    description: 'Desenvolvimento web, experiência do usuário (UX/UI), SEO, infraestrutura e estabilidade do portal.',
    managerId: 'usr-rafael',
    managerName: 'Rafael Mendes',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
];

export const INITIAL_POSITIONS: Position[] = [
  {
    id: 'pos-admin',
    title: 'Gerente Geral / Diretor Executivo',
    departmentName: 'Gerência Geral',
    description: 'Supervisão estratégica de todos os setores e liderança dos gerentes.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-mkt-mgr',
    title: 'Gerente de Marketing',
    departmentId: 'dept-marketing',
    departmentName: 'Marketing',
    description: 'Liderança do time de marketing, campanhas e aquisição.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-mkt-1',
    title: 'Especialista em Conteúdo & Mídia',
    departmentId: 'dept-marketing',
    departmentName: 'Marketing',
    description: 'Produção de conteúdo para redes sociais e materiais institucionais.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-mkt-2',
    title: 'Analista de Tráfego e Campanhas',
    departmentId: 'dept-marketing',
    departmentName: 'Marketing',
    description: 'Gestão de anúncios pagos, métricas de conversão e ROI.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-site-mgr',
    title: 'Gerente do Site & Web',
    departmentId: 'dept-site',
    departmentName: 'Site',
    description: 'Gestão da equipe de desenvolvimento do site, produto digital e métricas web.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-site-1',
    title: 'Designer UX/UI & Web',
    departmentId: 'dept-site',
    departmentName: 'Site',
    description: 'Design de interfaces, prototipagem e design system da plataforma.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-site-2',
    title: 'Desenvolvedor Front-end & Web',
    departmentId: 'dept-site',
    departmentName: 'Site',
    description: 'Implementação de interfaces web responsivas, componentes e APIs.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-com-mgr',
    title: 'Gerente Comercial',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    description: 'Gestão da equipe de vendas, metas comerciais e novos negócios.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-com-1',
    title: 'Executiva de Contas B2B',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    description: 'Prospecção e negociação direta com clientes corporativos.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pos-com-2',
    title: 'Consultor de Vendas',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    description: 'Atendimento a leads qualificados e fechamento de contratos.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  // 1. ADMIN / GERENTE GERAL
  {
    id: 'usr-admin',
    name: 'Matheus Manfroi',
    email: 'manfroimatheus3@gmail.com',
    role: 'admin',
    positionId: 'pos-admin',
    positionName: 'Gerente Geral / Diretor Executivo',
    departmentId: '',
    departmentName: 'Gerência Geral (Todos os Setores)',
    phone: '(11) 98765-4321',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    startDate: '2024-01-15',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },

  // 2. GERENTES DE CADA SETOR
  // Gerente do Site
  {
    id: 'usr-rafael',
    name: 'Rafael Mendes',
    email: 'rafael.site@empresa.com',
    role: 'manager',
    departmentId: 'dept-site',
    departmentName: 'Site',
    positionId: 'pos-site-mgr',
    positionName: 'Gerente do Site & Web',
    managerId: 'usr-admin',
    managerName: 'Matheus Manfroi',
    phone: '(11) 97654-3210',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    startDate: '2024-03-01',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  // Gerente de Marketing
  {
    id: 'usr-camila',
    name: 'Camila Rocha',
    email: 'camila.marketing@empresa.com',
    role: 'manager',
    departmentId: 'dept-marketing',
    departmentName: 'Marketing',
    positionId: 'pos-mkt-mgr',
    positionName: 'Gerente de Marketing',
    managerId: 'usr-admin',
    managerName: 'Matheus Manfroi',
    phone: '(11) 97123-4567',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    startDate: '2024-04-10',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  // Gerente Comercial
  {
    id: 'usr-bruno',
    name: 'Bruno Fagundes',
    email: 'bruno.comercial@empresa.com',
    role: 'manager',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    positionId: 'pos-com-mgr',
    positionName: 'Gerente Comercial',
    managerId: 'usr-admin',
    managerName: 'Matheus Manfroi',
    phone: '(11) 97234-5678',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    startDate: '2024-02-15',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },

  // 3. FUNCIONÁRIOS DO SETOR: SITE
  {
    id: 'usr-joao',
    name: 'João da Silva',
    email: 'joao.silva@empresa.com',
    role: 'employee',
    departmentId: 'dept-site',
    departmentName: 'Site',
    positionId: 'pos-site-1',
    positionName: 'Designer UX/UI & Web',
    managerId: 'usr-rafael',
    managerName: 'Rafael Mendes',
    phone: '(11) 96543-2109',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    startDate: '2024-08-10',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'usr-pedro',
    name: 'Pedro Duarte',
    email: 'pedro.duarte@empresa.com',
    role: 'employee',
    departmentId: 'dept-site',
    departmentName: 'Site',
    positionId: 'pos-site-2',
    positionName: 'Desenvolvedor Front-end & Web',
    managerId: 'usr-rafael',
    managerName: 'Rafael Mendes',
    phone: '(11) 96432-1098',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    startDate: '2024-09-01',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },

  // 4. FUNCIONÁRIOS DO SETOR: MARKETING
  {
    id: 'usr-amanda',
    name: 'Amanda Oliveira',
    email: 'amanda.oliveira@empresa.com',
    role: 'employee',
    departmentId: 'dept-marketing',
    departmentName: 'Marketing',
    positionId: 'pos-mkt-1',
    positionName: 'Especialista em Conteúdo & Mídia',
    managerId: 'usr-camila',
    managerName: 'Camila Rocha',
    phone: '(11) 95432-1098',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    startDate: '2025-02-01',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'usr-lucas',
    name: 'Lucas Prado',
    email: 'lucas.prado@empresa.com',
    role: 'employee',
    departmentId: 'dept-marketing',
    departmentName: 'Marketing',
    positionId: 'pos-mkt-2',
    positionName: 'Analista de Tráfego e Campanhas',
    managerId: 'usr-camila',
    managerName: 'Camila Rocha',
    phone: '(11) 95321-0987',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    startDate: '2025-03-15',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },

  // 5. FUNCIONÁRIOS DO SETOR: COMERCIAL
  {
    id: 'usr-juliana',
    name: 'Juliana Costa',
    email: 'juliana.costa@empresa.com',
    role: 'employee',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    positionId: 'pos-com-1',
    positionName: 'Executiva de Contas B2B',
    managerId: 'usr-bruno',
    managerName: 'Bruno Fagundes',
    phone: '(11) 94231-8765',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    startDate: '2024-11-01',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'usr-thiago',
    name: 'Thiago Martins',
    email: 'thiago.martins@empresa.com',
    role: 'employee',
    departmentId: 'dept-comercial',
    departmentName: 'Comercial',
    positionId: 'pos-com-2',
    positionName: 'Consultor de Vendas',
    managerId: 'usr-bruno',
    managerName: 'Bruno Fagundes',
    phone: '(11) 94123-7654',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    startDate: '2025-01-10',
    active: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
];

export const INITIAL_MEETINGS: Meeting[] = [
  // Reunião com Gerentes (Criada pelo Admin / Gerente Geral)
  {
    id: 'meet-gerentes',
    title: 'Alinhamento Geral com Gerentes de Setor',
    description: 'Reunião estratégica da gerência geral com os gestores dos 3 setores (Comercial, Marketing e Site) para alinhamento de metas e prioridades.',
    date: TODAY_ISO,
    time: '09:00',
    durationMinutes: 60,
    location: 'Sala da Diretoria / Google Meet Executivo',
    organizerId: 'usr-admin',
    organizerName: 'Matheus Manfroi (Gerente Geral)',
    type: 'Reunião com Gerentes',
    targetType: 'selected',
    targetParticipantIds: ['usr-admin', 'usr-bruno', 'usr-camila', 'usr-rafael'],
    status: 'scheduled',
    recurrence: 'weekly',
    recurrenceDescription: 'Toda segunda-feira às 09:00',
    agendaItems: [
      'Visão consolidada de resultados da empresa',
      'Desempenho e indicadores do Setor do Site',
      'Campanhas e geração de leads do Setor de Marketing',
      'Fechamentos e pipeline do Setor Comercial',
      'Definição de metas integradas entre os 3 setores',
    ],
    minutes: {
      summary: 'Alinhamento geral focado na integração dos 3 setores para o próximo trimestre.',
      topics: 'Sinergia entre campanhas de marketing e novos clientes no comercial; estabilidade do site.',
      decisions: 'Reuniões semanais entre gerentes às segundas-feiras; acompanhamento mensal de metas.',
      nextSteps: 'Gerentes consolidarem relatórios de cada setor.',
      notes: 'Excelente cooperação entre todas as lideranças dos setores Comercial, Marketing e Site.',
    },
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-08T10:00:00Z',
  },

  // 1:1 do Setor Site
  {
    id: 'meet-site-1',
    title: '1-on-1 de Desempenho e UX/UI',
    description: 'Acompanhamento do design system do novo portal e evolução profissional.',
    date: TODAY_ISO,
    time: '14:00',
    durationMinutes: 45,
    location: 'Sala de Reuniões 2',
    organizerId: 'usr-rafael',
    organizerName: 'Rafael Mendes',
    type: '1:1 (One on One)',
    targetType: 'individual',
    targetDepartmentId: 'dept-site',
    targetDepartmentName: 'Site',
    targetParticipantIds: ['usr-rafael', 'usr-joao'],
    status: 'scheduled',
    recurrence: 'biweekly',
    agendaItems: [
      'Revisão do design system no Figma',
      'Pontos positivos nas entregas do site',
      'Combinados para a próxima sprint',
    ],
    createdAt: '2026-09-05T11:00:00Z',
    updatedAt: '2026-09-05T11:00:00Z',
  },

  // Reunião do Setor Marketing
  {
    id: 'meet-mkt-1',
    title: 'Planejamento Semanal de Marketing',
    description: 'Revisão das campanhas ativas, produção de conteúdo e tráfego pago.',
    date: TOMORROW_ISO,
    time: '10:30',
    durationMinutes: 45,
    location: 'Sala Criativa / Meet',
    organizerId: 'usr-camila',
    organizerName: 'Camila Rocha',
    type: 'Reunião de Setor',
    targetType: 'department',
    targetDepartmentId: 'dept-marketing',
    targetDepartmentName: 'Marketing',
    targetParticipantIds: ['usr-camila', 'usr-amanda', 'usr-lucas'],
    status: 'scheduled',
    recurrence: 'weekly',
    agendaItems: [
      'Métricas de engajamento do Instagram e LinkedIn',
      'Otimização das campanhas do Google Ads',
      'Cronograma de postagens da semana',
    ],
    createdAt: '2026-09-06T09:00:00Z',
    updatedAt: '2026-09-06T09:00:00Z',
  },

  // Reunião do Setor Comercial
  {
    id: 'meet-com-1',
    title: 'Pipeline e Metas Comerciais',
    description: 'Análise de oportunidades em aberto, clientes enterprise e negociações.',
    date: '2026-09-12',
    time: '11:00',
    durationMinutes: 45,
    location: 'Sala Comercial',
    organizerId: 'usr-bruno',
    organizerName: 'Bruno Fagundes',
    type: 'Reunião de Setor',
    targetType: 'department',
    targetDepartmentId: 'dept-comercial',
    targetDepartmentName: 'Comercial',
    targetParticipantIds: ['usr-bruno', 'usr-juliana', 'usr-thiago'],
    status: 'scheduled',
    recurrence: 'weekly',
    agendaItems: [
      'Revisão do funil de vendas',
      'Contratos pendentes de assinatura',
      'Previsão de faturamento mensal',
    ],
    createdAt: '2026-09-06T09:00:00Z',
    updatedAt: '2026-09-06T09:00:00Z',
  },
];

export const INITIAL_FEEDBACKS: Feedback[] = [
  // Setor Site
  {
    id: 'fb-site-1',
    employeeId: 'usr-joao',
    employeeName: 'João da Silva',
    managerId: 'usr-rafael',
    managerName: 'Rafael Mendes',
    date: TODAY_ISO,
    type: 'Desempenho',
    category: 'Entrega Técnica e Qualidade Web',
    title: 'Feedback de consistência e prototipagem do site',
    description: 'Conversa focada na velocidade de entrega dos protótipos web e documentação dos componentes.',
    positivePoints: 'Excelente senso estético, agilidade nos componentes do Figma e colaboração técnica exemplar.',
    improvementPoints: 'Maior atenção na documentação dos estados de carregamento e mensagens de erro para os desenvolvedores.',
    agreements: 'Disponibilizar o guia de estados interativos junto com os wireframes aprovados.',
    notes: 'Colaborador muito receptivo e proativo nas melhorias.',
    needsFollowUp: true,
    followUpDaysOption: '15 dias',
    followUpDate: '2026-09-24',
    status: 'realizado',
    createdAt: '2026-09-09T09:00:00Z',
    updatedAt: '2026-09-09T09:00:00Z',
  },
  // Setor Marketing
  {
    id: 'fb-mkt-1',
    employeeId: 'usr-amanda',
    employeeName: 'Amanda Oliveira',
    managerId: 'usr-camila',
    managerName: 'Camila Rocha',
    date: '2026-09-02',
    type: 'Produtividade',
    category: 'Engajamento e Conteúdo',
    title: 'Criatividade e alcance das campanhas institucionais',
    description: 'Avaliação das métricas das últimas campanhas em redes sociais e artigos do blog.',
    positivePoints: 'Alta taxa de engajamento orgânico, excelente copywriting e autonomia na criação visual.',
    improvementPoints: 'Alinhar mais antecipadamente o calendário editorial com os lançamentos de novas funcionalidades do site.',
    agreements: 'Realizar reunião quinzenal de alinhamento entre Marketing e Site.',
    needsFollowUp: true,
    followUpDaysOption: '30 dias',
    followUpDate: '2026-10-02',
    status: 'realizado',
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-02T10:00:00Z',
  },
  // Setor Comercial
  {
    id: 'fb-com-1',
    employeeId: 'usr-juliana',
    employeeName: 'Juliana Costa',
    managerId: 'usr-bruno',
    managerName: 'Bruno Fagundes',
    date: '2026-09-05',
    type: 'Desempenho',
    category: 'Conversão Comercial B2B',
    title: 'Superação de meta mensal e atendimento corporativo',
    description: 'Reconhecimento pelo fechamento de 3 contas enterprise neste trimestre.',
    positivePoints: 'Postura consultiva, domínio do produto e excelente relacionamento com decisores.',
    improvementPoints: 'Manter o CRM atualizado com as notas de cada etapa de negociação para melhor previsão.',
    agreements: 'Registrar histórico detalhado no CRM no mesmo dia de cada reunião com clientes.',
    needsFollowUp: true,
    followUpDaysOption: '15 dias',
    followUpDate: '2026-09-20',
    status: 'realizado',
    createdAt: '2026-09-05T14:00:00Z',
    updatedAt: '2026-09-05T14:00:00Z',
  },
];

export const INITIAL_FOLLOW_UPS: FollowUp[] = [
  {
    id: 'fup-site-1',
    feedbackId: 'fb-site-1',
    feedbackTitle: 'Feedback de consistência e prototipagem do site',
    employeeId: 'usr-joao',
    employeeName: 'João da Silva',
    managerId: 'usr-rafael',
    managerName: 'Rafael Mendes',
    title: 'Acompanhamento: Guia de estados do site',
    scheduledDate: TODAY_ISO,
    status: 'Hoje',
    notes: 'Verificar se os estados de carregamento e erro foram documentados para os devs.',
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-09T08:00:00Z',
  },
  {
    id: 'fup-com-1',
    feedbackId: 'fb-com-1',
    feedbackTitle: 'Superação de meta mensal e atendimento corporativo',
    employeeId: 'usr-juliana',
    employeeName: 'Juliana Costa',
    managerId: 'usr-bruno',
    managerName: 'Bruno Fagundes',
    title: 'Acompanhamento: Atualizações do CRM Comercial',
    scheduledDate: '2026-09-20',
    status: 'Próximo',
    notes: 'Acompanhar se os registros de reuniões no CRM estão sendo feitos em tempo real.',
    createdAt: '2026-09-05T14:30:00Z',
    updatedAt: '2026-09-05T14:30:00Z',
  },
  {
    id: 'fup-mkt-1',
    feedbackId: 'fb-mkt-1',
    feedbackTitle: 'Criatividade e alcance das campanhas institucionais',
    employeeId: 'usr-amanda',
    employeeName: 'Amanda Oliveira',
    managerId: 'usr-camila',
    managerName: 'Camila Rocha',
    title: 'Acompanhamento: Calendário de campanhas',
    scheduledDate: '2026-10-02',
    status: 'Próximo',
    notes: 'Verificar alinhamento do cronograma editorial com as entregas da equipe do Site.',
    createdAt: '2026-09-02T10:30:00Z',
    updatedAt: '2026-09-02T10:30:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  // Tarefa Setor Site
  {
    id: 'tsk-site-1',
    title: 'Atualizar componentes do design system do site',
    description: 'Documentar botões, modais e campos de texto com suporte a tema escuro.',
    assigneeId: 'usr-joao',
    assigneeName: 'João da Silva',
    creatorId: 'usr-rafael',
    creatorName: 'Rafael Mendes',
    dueDate: TODAY_ISO,
    priority: 'Alta',
    status: 'Em andamento',
    originType: 'feedback',
    originTitle: 'Feedback de consistência - 09/09',
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-08T11:00:00Z',
  },
  {
    id: 'tsk-site-2',
    title: 'Otimizar tempo de carregamento da página inicial',
    description: 'Comprimir imagens SVG e implementar lazy loading nos módulos do portal.',
    assigneeId: 'usr-pedro',
    assigneeName: 'Pedro Duarte',
    creatorId: 'usr-rafael',
    creatorName: 'Rafael Mendes',
    dueDate: TOMORROW_ISO,
    priority: 'Alta',
    status: 'Pendente',
    originType: 'direct',
    originTitle: 'Acordo Direto de Gestão',
    createdAt: '2026-09-08T14:00:00Z',
    updatedAt: '2026-09-08T14:00:00Z',
  },
  // Tarefa Setor Marketing
  {
    id: 'tsk-mkt-1',
    title: 'Lançar campanha de tráfego pago para novos clientes',
    description: 'Configurar novos anúncios segmentados no Google Ads e Meta Ads com foco em B2B.',
    assigneeId: 'usr-lucas',
    assigneeName: 'Lucas Prado',
    creatorId: 'usr-camila',
    creatorName: 'Camila Rocha',
    dueDate: TODAY_ISO,
    priority: 'Alta',
    status: 'Em andamento',
    originType: 'meeting',
    originTitle: 'Planejamento de Marketing',
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-08T17:00:00Z',
  },
  // Tarefa Setor Comercial
  {
    id: 'tsk-com-1',
    title: 'Enviar proposta personalizada para Grupo Alfa',
    description: 'Consolidar escopo de implementação e proposta comercial com tabela de descontos.',
    assigneeId: 'usr-juliana',
    assigneeName: 'Juliana Costa',
    creatorId: 'usr-bruno',
    creatorName: 'Bruno Fagundes',
    dueDate: TODAY_ISO,
    priority: 'Urgente',
    status: 'Pendente',
    originType: 'meeting',
    originTitle: 'Pipeline e Metas Comerciais',
    createdAt: '2026-09-08T16:00:00Z',
    updatedAt: '2026-09-08T16:00:00Z',
  },
];

export const INITIAL_FEEDBACK_REQUESTS: FeedbackRequest[] = [
  {
    id: 'req-1',
    employeeId: 'usr-joao',
    employeeName: 'João da Silva',
    managerId: 'usr-rafael',
    managerName: 'Rafael Mendes',
    topic: 'Alinhamento sobre design system e novos projetos do Site',
    message: 'Gostaria de avaliar com você os resultados dos novos protótipos e próximos desafios.',
    status: 'requested',
    createdAt: '2026-09-08T10:30:00Z',
    updatedAt: '2026-09-08T10:30:00Z',
  },
  {
    id: 'req-2',
    employeeId: 'usr-amanda',
    employeeName: 'Amanda Oliveira',
    managerId: 'usr-camila',
    managerName: 'Camila Rocha',
    topic: 'Feedback sobre nova campanha de marketing',
    message: 'Gostaria de entender se as novas artes estão aderentes à diretriz da gerência.',
    status: 'viewed',
    createdAt: '2026-09-07T14:15:00Z',
    updatedAt: '2026-09-08T09:00:00Z',
  },
];

export const INITIAL_CONVERSATION_REQUESTS: ConversationRequest[] = [
  {
    id: 'creq-1',
    employeeId: 'usr-juliana',
    employeeName: 'Juliana Costa',
    managerId: 'usr-bruno',
    managerName: 'Bruno Fagundes',
    type: 'Conversa sobre carreira',
    message: 'Gostaria de conversar sobre oportunidades de liderança de contas estratégicas.',
    status: 'requested',
    createdAt: '2026-09-08T16:00:00Z',
    updatedAt: '2026-09-08T16:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'usr-admin',
    title: 'Reunião com Gerentes de Setor',
    message: 'Reunião de alinhamento com os gerentes do Comercial, Marketing e Site hoje às 09:00.',
    type: 'meeting',
    read: false,
    createdAt: '2026-09-09T08:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'usr-rafael',
    title: 'Convocação: Reunião com a Gerência Geral',
    message: 'Matheus Manfroi (Gerente Geral) agendou reunião estratégica com os gerentes hoje às 09:00.',
    type: 'meeting',
    read: false,
    createdAt: '2026-09-09T08:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'usr-camila',
    title: 'Convocação: Reunião com a Gerência Geral',
    message: 'Matheus Manfroi (Gerente Geral) agendou reunião estratégica com os gerentes hoje às 09:00.',
    type: 'meeting',
    read: false,
    createdAt: '2026-09-09T08:00:00Z',
  },
  {
    id: 'notif-4',
    userId: 'usr-bruno',
    title: 'Convocação: Reunião com a Gerência Geral',
    message: 'Matheus Manfroi (Gerente Geral) agendou reunião estratégica com os gerentes hoje às 09:00.',
    type: 'meeting',
    read: false,
    createdAt: '2026-09-09T08:00:00Z',
  },
  {
    id: 'notif-6',
    userId: 'usr-joao',
    title: '1-on-1 agendado hoje às 14:00',
    message: 'Você tem reunião 1:1 de acompanhamento com Rafael Mendes.',
    type: 'meeting',
    read: false,
    createdAt: '2026-09-09T08:15:00Z',
  },
];
